version: '3.8'
services:
  oracle-db:
    image: container-registry.oracle.com/database/enterprise:12.2.0.1
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      ORACLE_SID: ORCLCDB
      ORACLE_PDB: ORCLPDB1
      ORACLE_PWD: your_password
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - oracle_data:/opt/oracle/oradata

volumes:
  oracle_data:
